apiVersion: v2
appVersion: "1.17"
description: Google Cloud SQL Proxy
engine: gotpl
home: https://cloud.google.com/sql/docs/postgres/sql-proxy
keywords:
- google
- cloud
- postgresql
- mysql
- sql
- sqlproxy
maintainers:
- email: jadeteam@broadinstitute.org
  name: Jade
name: gcloud-sqlproxy
sources:
- https://github.com/broadinstitute/datarepo-helm
version: 0.19.12
