{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cron-job.serviceAccountName" . }}
  labels:
{{ include "cron-job.labels" . | nindent 4 }}
{{- end -}}
