{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oidc-proxy.serviceAccountName" . }}
  labels:
{{ include "oidc-proxy.labels" . | nindent 4 }}
{{- end -}}
